# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Applucation-Plus
version:      1
version_from: lib/CGI/Application/Plus.pm
installdirs:  site
requires:
    Class::constr:                 1.52
    Class::props:                  1.52
    Object::props:                 1.52

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
